### PR TITLE
update files to add mobile menu, fix styles

### PR DESCRIPTION
**Pull request by thecristen**
The biggest update here is the mobile menu is now added (and working!)

Other updates:
* The HTML output isn't so pretty anymore. I had to stop using the pretty format because it was adding extra whitespace around text, and that whitespace was making certain parts of our navigation look all wonky!

### CODE REVIEW

**Comment by lund5000** [comment]
Much improved! The only issue I can see now is that the search icon is still included at <544px wide.

Screen Shot 2022-04-07 at 1 37 20 PM

**Comment by thecristen** [comment]
Thanks @lund5000! I tried to fix this with this latest commit.

**Comment by lund5000** [comment]
Search bar: fixed!

One last thing to point out: this doesn't happen when resizing to a small viewport on desktop, but when I test on my iPhone the width of the header shrinks when I open the mobile menu. Closing the menu restores everything to the full width. Maybe this won't be an issue when embedded on the actual page with other CSS rules about page layout and width?

header-page-width

**Comment by thecristen** [comment]
Ah I see, great catch. I think you're right that it might not pose an issue in a real website that presumably has reasonably defined html/body width defined. @lund5000 Are we comfortable with pushing as is, and if we hear it's causing issues we can debug and adjust as needed?

**Review by lund5000 — APPROVED** [review]

**Pull request merged**
