### PR TITLE
refactor: make this project easier to preview locally

### PR DESCRIPTION
**Pull request by ryan-mahoney**
No ticket.

I wanted to make this easier to review and ran into a few snags running this locally.

This biggest change was removing the `Makefile`. For this use case, I don't think we were getting an advantage from make over a regular bash script and I was running into some issues with paths when running on Linux.

### CODE REVIEW

**Comment by ryan-mahoney** [comment]
cc @paulswartz I don't think this is the right solution, but in spirit, a project like this could/should be the basis for a unified header for applications such as:
- reduced fares
- my charle
- t-alerts, etc

**Review by paulswartz — COMMENTED** [review]
question: what version of NodeJS should this use? I don't see a `.tool-versions` or `.nvmrc`.

**Comment by ryan-mahoney** [comment]
> question: what version of NodeJS should this use? I don't see a `.tool-versions` or `.nvmrc`.

@paulswartz good catch. @thecristen mentioned this in AM as well and I forgot. Aligning to the current LTS version

**Review by thecristen — APPROVED** [review]
I added a commit to fix a filename reference, and then it all worked! Thanks for adding this @ryan-mahoney

**Pull request merged**
